-- ============================================================================
-- 0019 — rate-limit ledger for public Edge Functions (e.g. the contact form).
-- RLS on with NO policies → anon/authenticated have zero access; only the
-- service role (used inside Edge Functions) reads/writes it. Idempotent.
-- ============================================================================
create table if not exists public.rate_limits (
  id     bigint generated by default as identity primary key,
  bucket text not null,
  ip     text not null,
  at     timestamptz not null default now()
);
create index if not exists rate_limits_lookup_idx on public.rate_limits (bucket, ip, at desc);
alter table public.rate_limits enable row level security;
